language: node_js
node_js:
  - "10"
  - "12"
before_install:
  - npm install -g yarn
  - pip install --user awscli
install:
  - yarn install
stages:
  - name: "Test"
  - name: "Deploy"
    if: tag IS present
jobs:
  include:
    - stage: "Test"
      name: "lint"
      script: "yarn lint"
    - name: "cli: unit tests"
      script: "yarn workspace zapier-platform-cli test"
    - name: "cli: smoke tests"
      script: "yarn workspace zapier-platform-cli smoke-test"
    - name: "core: unit tests"
      script: "yarn workspace zapier-platform-core test"
    - name: "core: smoke tests"
      script: "yarn workspace zapier-platform-core smoke-test"
    - name: "schema: unit tests"
      script: "yarn workspace zapier-platform-schema test"
    - name: "schema: smoke tests"
      script: "yarn workspace zapier-platform-schema smoke-test"
    - name: "legacy-scripting-runner: integration tests"
      script: "yarn workspace zapier-platform-legacy-scripting-runner test"
    - stage: "Deploy"
      script: skip
      deploy:
        provider: script
        script: ./scripts/publish.sh
        on:
          tags: true,
          node: "12"
        skip_cleanup: true
notifications:
  email: false
env:
  global:
    - PATH: PATH=$HOME/.local/bin:$PATH
