language: node_js
node_js:
  - '8.10'
  - '10'
before_install:
  - npm install -g yarn
  - pip install --user awscli
install:
  # need to ignore engines until we can ditch node 8 after calendar 2019
  - yarn install --ignore-engines
script:
  - yarn test
  - yarn smoke-test
notifications:
  email: false
deploy:
  provider: script
  script: ./scripts/publish.sh
  on:
    tags: true
    node: '8.10'
  skip_cleanup: true
env:
  global:
    - PATH: PATH=$HOME/.local/bin:$PATH
    - secure: NluPsZ79rj8QfRFAGrUuM2VFOTa2uj15FScR0SDSFKOCDAznoK2FJCX//y6rovI0P1p8MddSMdlfE+fo/nA9XXjFh2vLlMoLbSGjU/3R1/0+2A725PynC8GSyxroDyd+3McUgUoGkzh1B6Wn4kpg/1RrqWivT2mMqZq7Ojupi3GjLpvmikjMqEPDbE6EGGhIUK1Z/UdLQFr2iqbXK/Rp0iQGU9R+JOJM46vuC0AFo4bveHg6CqCkN5+akg4vMfVg7J+pwOtCFPOFOOvYpI2q5dSwlqf4+lmzTog3fnoviSYULQFsGmxdH38nRI25OxTdeMlt1nUSPYsezxnj+3bs/TlHxORFJrjiaDW/UA/43IfAPfx0735lJDEoyeKEe4CdiPWdtUCTlgcAvptN19J2YvfIctZdNVKctDtOJ2R/1yK+EFb1jAuP9TezmW7fLQyPxhebuwsSiLcJw/+7Ri5ZGRYC71QAqcUh+/mvn4dkDmrJNGbhZMLdS2Qz1bMOHru60JcnZj7+T7JTy1wjLIW7hUqEHU6qLZ1ERrQcgGLtqPiIEgQ454PWPBlQUr7kk8h60SyN9CwwyNr7CM2whdrBqN0Q83y6xnbREbNlILoFzYpAWoNCE2n/KOS58GWcRH/Qc+iIkARxjaFpSeU3yAcwNchynHG/ddxVMmoEm1CZVf0=
    - secure: KHS7tk56Cxa1TudJGJ7M/jHWXwnBILKGE0lH8tCrKYxjq69gwXdO72tA2+Ur/j8+GsEbLinmN77vfE34D+rGpoJAsKlvOyZ8xovdwjEgDru7O3WQvqLQxSCPO/ASliCIbmapfeDBoumaJoHNRUJrEnlR6WTD3DanxRChhmJPzh+sZrQhwEJF+CQy6rWd5pVzmHtIZyWjyj5QK2qF83ZO15fcqUqK8O0w9ZRpi7AjVwv10mq4Lz/f2Gl/d6eLXpNl0wAh0xeCaWFMNdYbzPbzVeifzvJWDqDn/RNeUeTCZNTe0gik4X3AUnoTMK0rrGPIb3D10wDy1uQpyDZuKpif5fIMTt81tEf48xCws1ihm9HJdCio8i3mI4Q4YRILFNcmL70qYIoGzDrlbW/VbZ0+FKU1f4lSa88tnYenQMX0EXFU88Iyw3YHlu2vgq8ys7AMM7LOEzF7fOCA8uBBJtcLwg/1ROFQWKG4eI1qTU6NmyKZsmq9uJZ6LIrwo1cI5TOgV3i6zUgRbVw9LMBzORXHNGc5h3kfLgQLUCZGxPGB4ltuH9Poe/W/YA4j0FoNdSLahb6qU/iFz/qK04mFdNcncSqRe1IkScxLx+Tr/d7oDhZN0pWs52C6zTwXlTGxlGmd39a51wHlxZlQsi+7XbY6asRqrCn5lTPyucoqpNZmm5A=
