language: node_js
node_js:
  - "14"
cache:
  - npm: true
  - yarn: true
  - pip: true
before_install:
  - npm install -g yarn
  - pip install --user awscli
install:
  - yarn install
stages:
  - name: "Test"
  - name: "Deploy"
    if: tag IS present
jobs:
  include:
    - stage: "Test"
      name: "lint"
      script: "yarn lint"
      node_js: "14"
    - name: "unit tests - Node 12"
      script: "yarn test"
      node_js: "12"
    - name: "unit tests - Node 14"
      script: "yarn test"
      node_js: "14"
    - name: "smoke tests - Node 12"
      script: "yarn smoke-test"
      node_js: "12"
    - name: "smoke tests - Node 14"
      script: "yarn smoke-test"
      node_js: "14"
notifications:
  email: false
env:
  global:
    - PATH: PATH=$HOME/.local/bin:$PATH
