language: node_js
node_js:
  - '10.16.3' # lambda version as of 2019-11-21
before_install:
  - npm install -g yarn
  - pip install --user awscli
install:
  # need to ignore engines until we can ditch node 8 after calendar 2019
  - yarn install --ignore-engines
script:
  - yarn validate
notifications:
  email: false
deploy:
  provider: script
  script: ./scripts/publish.sh
  on:
    tags: true
    node: '10.16.3'
  skip_cleanup: true
env:
  global:
    - PATH: PATH=$HOME/.local/bin:$PATH
    - secure: ZWLlcTLLmCvTpbiUx7BQNEdUHug9bHk9Fz0QFsmpLBcLEPETvKLIMGyC1RKsR50maZ/fILw2pDtlwchR53dKQgxroh1Iv323SnB/+zZwjoK9v//gpOlg/wYnqLDb2mGNc8giphV3OOJo49m0rZ32EElxVTDen3Wa7Ar/QyKvHPQwhhuup17aZBvEYBAU/kQt5L4c/cP8W9WVN7QXSowynWZ65wCfQiWAoGfLsfonkhpEIIKqW65Yo5UUUlWMQ+fyn2MmgEd4GE2s9Km1935xcDJAaw4jTcVoVb2vE2wVt05k0byYR+h1ewP7CwleMq51Cul4jVycDAmRz0TblvF+n5jr1xRZna9VhmMjflNOz0zF7loluLZQNEdK5rcyIPNfqH3FI1o9KTfvF6iRvEULGEqx2iIm7zNkD+jalBESFsRudIM+PFX5Eh3rVNFFLMU5316M4ubcg5RlhdZ/agNBuH4GAm0Gey2bOz3DWM/eD7TY+IFLrBMLWd7BueneaSl6EKocC4G9dNaZj8lqv/eKlHEww8l7Fg2kIrS4E+ih6KWyFbTqyHu/ZaNiUowFxaRL4zZCa7YTyuWSv7Ubon0hGu1otQbj1k4Lhxh2PaC2rBzHrI+IhBT4GIlMV9BMGTXH3o4QAthmW4Ch3SqcTXRQ4P0rmboWB91bJz6t+txNZu4=
    - secure: wHuQQCagSVSjrFD+vvpSpjgwlXpyVmAaZNyYa38AR46SSc9YhXkq+PIaA5OcxyTzE45c91YOIbnwee+o1UyJqbaB0lWNMgKsNzFaDEAeL3rUyuRAz92RFn1pM9mqu+ExKlgLnHJXCPfpijyKM+WKfoq3LBwLQMG44ogwsM30e+4eDSuJiv5q4cPnOp56x+BwJbsW9ifJxQKZTQzwHm3KZfCnexaBglftLmFDtX0SQ8NSsrvm47WBNmBpclNVLyoj92hpCrB5YIcOL5WxCMw1cjmm/q6dh6G5UvQ72AQsIuOfm4DXncP3tOq14lpVQJTxdg8Vjw6cVO4PdyInNiebm9hyiJIcPRV+wLX1jGhfZNvJpjVaMqsdcBJDzWnGXbhrvC6F2CD0w9b8MclHn2V5Tw9gPEWU/953Lc1U+CdqVCuhz1tcpoiqLJqMqtkyOqr4Wbea8HOqRtNudLZCCH9v5sngNqPwAUdKQkKuzs6usRpsQxAPvCr1nNNz7x5a+tUpbm76C+GwOcu/acZhZfMzAex0H05jax+ixl+i9I1M3SRGoPpJ/SZHZGYa6fFpB/owMMbjb74s+H+FkWwmOB/eOZ/yNPMxYz/5hgqqzCkX2fmPytGOP+4lDw/4gwQpzjLk1NlulRFA1wXuHn/Bsm3OvvVNPt7jaUJFMShgw+JZNU8=
