language: node_js
node_js:
  - "6.10.3"
  - "7"
  - "8"
notifications:
  email: false
deploy:
  - provider: npm
    email: engineering@zapier.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "zapier-dev-platform-cli-boilerplates"
    acl: private
    local_dir: "build-boilerplate"
    skip_cleanup: true
  on:
    tags: true
    node: "6.10.3"
before_deploy:
  - npm run build-boilerplate
